### ISSUE TITLE
deployment issue can't evaluate field FNV32a in type interface {}

### ISSUE THREAD

**Issue by Masabu** [bep/gallerydeluxe_starter#10]
I had hugo and gallerydeluxe successfully working and build site on my Mac and Ubuntu but not working on my newly installed Ubuntu. 

I git cloned : gallerydeluxe_starter - and when i compile it - it returns error like below- any clues?

go version go1.18.1 linux/arm64
hugo v0.92.2+extended linux/arm64 BuildDate=2023-01-31T11:11:57Z VendorInfo=ubuntu:0.92.2-1ubuntu0.1

:hugo
Start building sites … 
hugo v0.92.2+extended linux/arm64 BuildDate=2023-01-31T11:11:57Z VendorInfo=ubuntu:0.92.2-1ubuntu0.1
Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:23:17: executing "index.html" at <partial "gallerydeluxe/init.html" (dict "images" $images)>: error calling partial: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/bep/gallerydeluxe@v0.10.0/layouts/partials/gallerydeluxe/init.html:22:35": execute of template failed: template: partials/gallerydeluxe/init.html:22:35: executing "partials/gallerydeluxe/init.html" at <crypto>: can't evaluate field FNV32a in type interface {}

**Comment by bep** [comment]
>hugo v0.92.2+extended linux/arm64 

You need a newer Hugo version.

**Comment by Masabu** [comment]
thank you, i upgraded hugo and it worked all good!!

**Comment by Masabu** [comment]
resolved by upgrading hugo to the newer version
