### ISSUE TITLE
issue with bundle ID generation or slice of photos

### ISSUE THREAD

**Issue by wojakcafe** [bep/gallerydeluxe_starter#11]
This happens when I follow the install instructions of "use this template" - create a name for it, adjust config.toml and go.mod, etc. I have not replaced any of the images included. I cannot serve the site, hugo terminates after the Built message.

```
Start building sites … 
hugo v0.92.2+extended linux/amd64 BuildDate=2023-01-31T11:11:57Z VendorInfo=ubuntu:0.92.2-1ubuntu0.1
Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:23:17: executing "index.html" at <partial "gallerydeluxe/init.html" (dict "sourcePath" "images")>: error calling partial: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/bep/gallerydeluxe@v0.11.1/layouts/partials/gallerydeluxe/init.html:22:35": execute of template failed: template: partials/gallerydeluxe/init.html:22:35: executing "partials/gallerydeluxe/init.html" at <crypto>: can't evaluate field FNV32a in type interface {}
Built in 36 ms
```

My go.mod:
```
module github.com/wojakcafe/imagegallery

go 1.19

require github.com/bep/gallerydeluxe v0.11.1 // indirect
```

My config.toml is essentially unchanged besides title.

hugo v0.92.2+extended linux/amd64 BuildDate=2023-01-31T11:11:57Z VendorInfo=ubuntu:0.92.2-1ubuntu0.1
go1.18.1 linux/amd64

I'm going to try adding a repo for a newer version of go that will match with the 1.19 expected and see if that fixes it.

**Comment by bep** [comment]
You need to upgrade Hugo to >= v0.98.0 (where that template func was added).
