### ISSUE TITLE
Noob issue

### ISSUE THREAD

**Issue by jthack** [bep/gallerydeluxe_starter#4]
Hello,

I've never deployed a hugo site. I've followed in the instructions in the readme and then when i run hugo, i get this:

```
❯ hugo                                                                                                             х INT
go: no module dependencies to download
Start building sites …
hugo v0.108.0+extended darwin/amd64 BuildDate=unknown
Error: Error building site: failed to render pages: render of "home" failed: "/Users/home/git/hackers/layouts/index.html:10:7": execute of template failed: template: index.html:10:7: executing "index.html" at <partial "gallerydeluxe/head.html" .>: error calling partial: partial "gallerydeluxe/head.html" not found
Total in 1869 ms
```

**Comment by bep** [comment]
What's the output of `go version`?

**Comment by jthack** [comment]
go version go1.18 darwin/amd64

**Comment by bep** [comment]
Can you point me to your GitHub repo?

I just tested this starter here:

https://github.com/bep/testgdeluxe

And that works fine for me. You could also try to clone the above repo and run `hugo server` in it.

**Comment by SaGuse** [comment]
had the same issue like @jthack, in my first steps ich tried to recreate my own project, and copy paste all code from this repo

i solved the problem with cloning this repo, after that i could change the options locally and run the gallery

**Comment by recycleleash** [comment]
I have an issue when deploying the static app to azure. Here is the output I get from git. Locally, it’s working fine with “Hugo serve”
![8FEE7FB7-E7C9-4FC5-B0B2-B231C8729FCD](https://user-images.githubusercontent.com/99685393/223605349-f268eae0-3843-4282-92da-f2c477e10dd5.png)
![E0142158-1926-4AA5-819C-E8ED41B8E8F2](https://user-images.githubusercontent.com/99685393/223605424-8cf103d0-1c2f-4783-953d-5a930ee3539a.jpeg)

**Comment by bep** [comment]
I thought I added a version check for that ... Oh well, it fails because the version used on Azure is too old (0.96 is pretty old). The `.Colors` method was introduced in v0.104.0. I don't know Azure well enough to say, but usually you can control this via a `HUGO_VERSION` or something.
