### ISSUE TITLE
Images inside content/images

### ISSUE THREAD

**Issue by icifra** [bep/gallerydeluxe_starter#5]
I installed the theme as a module, added images to content/images and configured config.
Along with this, I get images of cars :) that are not editable.
What is misconfigured?

**Comment by bep** [comment]
Don't you like my car photos? :-) 

This repository is a _starter template_ and is not meant to be used as a theme. Under the hood it uses `github.com/bep/gallerydeluxe` as the theme.

My idea was that people would:

* Clone or hit the `use this template` button on GitHub
* Name the repository to be the name of the new site (e.g. `mycoolgallery`)
* Remove all the car images inside /content and replace with own.

A little simplified. Let me know if that didn't clear up things.

**Comment by icifra** [comment]
This fleet should only consist of super fast cars, just like Hugo!

I immediately did the same with the main theme, now I see "nothing" :)

It can't be installed as a Hugo module?

**Comment by bep** [comment]
>It can't be installed as a Hugo module?

The _theme_ can, which this repo should be a great example.

**Comment by icifra** [comment]
And why can't I get the site if the following is done:

Project initialized and module added 
`[module]
[[module.imports]]
  path = 'github.com/bep/gallerydeluxe'`

Configuration Defined
`[params]
    [params.gallerydeluxe]
        shuffle = false
        reverse = false
        enable_exif = false`

.png added to content/images

Now I agree to your cars :)

**Comment by Kiainigenk** [comment]
btw i have one question how do i remove the car images im a noob btw

**Comment by bep** [comment]
>btw i have one question how do i remove the car images im a noob btw

You delete them.
