### ISSUE TITLE
The starter gallery does not build...

### ISSUE THREAD

**Issue by rsyncOSX** [bep/gallerydeluxe_starter#7]
Start building sites …
hugo v0.110.0+extended darwin/arm64 BuildDate=unknown
Error: Error building site: failed to render pages: render of "home" failed: "/Users/thomas/Downloads/gallerydeluxe_starter-main/layouts/index.html:10:7": execute of template failed: template: index.html:10:7: executing "index.html" at <partial "gallerydeluxe/head.html" .>: error calling partial: partial "gallerydeluxe/head.html" not found

**Comment by bep** [comment]
So, it does build fine, one example can be seen here:

https://gallerydeluxe.netlify.app/

* Have you followed the insturctions in the readme?
* Are you sure you're not seeing any other error messages?
* What's your Go version? (oautput of `go version`)?

**Comment by rsyncOSX** [comment]
I am using Homebrew, all packages are updated to latest.. I found your gallery few days ago, tested it and the build worked OK. Tried another build today and the above issue occurred, no changes at all to code. Downloaded your starter project (as a zip file), tried to build but failed with same issue as above...

**Comment by bep** [comment]
Just tested a new clone here https://github.com/bep/deleteme1

Works good.

I could maybe speculate that your Hugo Modules cache somehow got corrupted.

What you can try (and what I also would recommend) is that you set the `HUGO_CACHEDIR` OS env variable to point to some directory outside of /tmp. And then try to run again. Other things to try would be `hugo mod clean` and `hugo mod clean --all`.

**Comment by rsyncOSX** [comment]
Hi and thx, `hugo mod clean` did the magic. Closing the issue. 
Thx for help and gallery..

**Comment by rsyncOSX** [comment]
I have just commenced adding pictures to gallery, more will come.. I also have another Hugo site with bird pics, I am converting all pics by PhotoLab - it will take some time but and the gallery is a start.. Have been looking for such a Hugo module for long time, great work with both Hugo and the gallery module.. 

https://gallerybythomas.netlify.app
