### ISSUE TITLE
failed to deploy started site in azure

### ISSUE THREAD

**Issue by recycleleash** [bep/gallerydeluxe_starter#8]
looking at some of the other issues i ran "hugo mod clean" and this  does not resolve the issue.

Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:19:17: executing "index.html" at <partial "gallerydeluxe/init.html" (dict "sourcePath" "images")>: error calling partial: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/bep/gallerydeluxe@v0.9.2/layouts/partials/gallerydeluxe/init.html:27:22": execute of template failed: template: partials/gallerydeluxe/init.html:27:22: executing "partials/gallerydeluxe/init.html" at <$20.Colors>: can't evaluate field Colors in type *resources.resourceAdapter

Thanks

**Comment by bep** [comment]
You need a reasonably new Hugo version (>= Hugo 0.104 I think). I don't know Azure, but I suspect you can set the Hugo version in a `HUGO_VERSION` env var or something.

**Comment by recycleleash** [comment]
looks like there are no places to add this in Azure. I went ahead and tried to deploy in Netlify, no problems there!

https://photos.recycleleash.com

thanks!!

**Comment by bep** [comment]
Hmm... According to this section, that should be possible:

https://learn.microsoft.com/en-us/azure/static-web-apps/publish-hugo#custom-hugo-version

Oh well, Netlify is also great.
